import Quickshell
import Quickshell.Wayland
import QtQuick
import QtQuick.Layouts

// We use a RowLayout to contain the icons generated by the Repeater
RowLayout {
    spacing: 8
    
    Repeater {
        // 1. The Model: This is the live list of all open windows
        model: ToplevelManager.toplevels

        // 2. The Delegate: This is the template for each individual app icon
        delegate: Rectangle {
            id: iconWrapper
            
            // Layout properties for the RowLayout
            Layout.preferredWidth: 42
            Layout.preferredHeight: 42
            
            radius: 8
            // Visual feedback: Highlight the background if the window is focused
            color: modelData.active ? Qt.rgba(1, 1, 1, 0.2) : "transparent"

            Image {
                anchors.fill: parent
                anchors.margins: 4
                
                // 3. The Icon Logic: Map the appId to a system icon path
                source: Quickshell.iconPath(modelData.appId) || "icon-missing"
                fillMode: Image.PreserveAspectFit
            }

            // 4. The Interaction: Clicking the icon focuses the window
            MouseArea {
                anchors.fill: parent
                onClicked: modelData.activate()
                
                cursorShape: Qt.PointingHandCursor
            }
            
            // Small indicator dot at the bottom for active apps
            Rectangle {
                anchors.bottom: parent.bottom
                anchors.horizontalCenter: parent.horizontalCenter
                anchors.bottomMargin: 2
                width: 4; height: 4
                radius: 2
                color: "white"
                visible: modelData.active
            }
        }
    }
}
